// <auto-generated>
//   Generated from live FFXIV game data (Action / Item / EurekaMagiciteItem sheets)
//   cross-referenced with the public recipe tables at https://ffxiv-eureka.com/logograms.
//   Do not edit by hand. Regenerate with the tooling described in Data/README.md.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace Logoria.Data
{
    public enum LogosActionKind
    {
        Ability,
        Spell,
        Weaponskill,
    }

    /// <summary>One mneme requirement within a recipe.</summary>
    public sealed record MnemeSlot(uint ItemId, int Count);

    /// <summary>One way to synthesise an action. Fewer slots means a higher success rate.</summary>
    public sealed record LogosRecipe(IReadOnlyList<MnemeSlot> Slots)
    {
        public int TotalMnemes
        {
            get
            {
                var n = 0;
                foreach (var s in Slots) n += s.Count;
                return n;
            }
        }
    }

    public static class LogosDatabase
    {
        public static readonly IReadOnlyList<LogosAction> Actions = new LogosAction[]
        {
            new(
                actionId: 12958,
                magiaIndex: 1,
                fallbackName: "Wisdom of the Aetherweaver",
                iconId: 64601,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "magicDmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24015, 1) }),
                }),
            new(
                actionId: 12959,
                magiaIndex: 2,
                fallbackName: "Wisdom of the Martialist",
                iconId: 64602,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "dmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24016, 1) }),
                }),
            new(
                actionId: 12960,
                magiaIndex: 3,
                fallbackName: "Wisdom of the Platebearer",
                iconId: 64603,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "mnk", "drg", "brd", "whm", "blm", "smn", "nin", "mch", "ast", "sam", "rdm", "dnc" },
                tags: new[] { "def", "maxHP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24017, 1) }),
                }),
            new(
                actionId: 12961,
                magiaIndex: 4,
                fallbackName: "Wisdom of the Guardian",
                iconId: 64604,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "def", "maxHP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24018, 1) }),
                    new(new MnemeSlot[] { new(24017, 1), new(24022, 1) }),
                    new(new MnemeSlot[] { new(24017, 1), new(24035, 1) }),
                    new(new MnemeSlot[] { new(24017, 1), new(24037, 2) }),
                    new(new MnemeSlot[] { new(24035, 3) }),
                }),
            new(
                actionId: 12962,
                magiaIndex: 5,
                fallbackName: "Wisdom of the Ordained",
                iconId: 64605,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "maxMP", "healingMagicPotency", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24019, 1) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24036, 1) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24033, 2) }),
                    new(new MnemeSlot[] { new(24034, 3) }),
                }),
            new(
                actionId: 12963,
                magiaIndex: 6,
                fallbackName: "Wisdom of the Skirmisher",
                iconId: 64606,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "mnk", "drg", "brd", "blm", "smn", "nin", "mch", "sam", "rdm", "dnc" },
                tags: new[] { "dmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1) }),
                    new(new MnemeSlot[] { new(24016, 1), new(24028, 1) }),
                    new(new MnemeSlot[] { new(24016, 3) }),
                }),
            new(
                actionId: 12964,
                magiaIndex: 7,
                fallbackName: "Wisdom of the Watcher",
                iconId: 64607,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "eva", "dmg", "buff", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24029, 2) }),
                }),
            new(
                actionId: 12965,
                magiaIndex: 8,
                fallbackName: "Wisdom of the Templar",
                iconId: 64608,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "healingMagicPotency", "maxHP", "dmg", "buff", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1), new(24034, 1) }),
                    new(new MnemeSlot[] { new(24020, 1), new(24035, 1) }),
                    new(new MnemeSlot[] { new(24017, 1), new(24033, 1), new(24035, 1) }),
                }),
            new(
                actionId: 12966,
                magiaIndex: 9,
                fallbackName: "Wisdom of the Irregular",
                iconId: 64609,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "mnk", "drg", "brd", "blm", "smn", "nin", "mch", "sam", "rdm", "dnc" },
                tags: new[] { "dmg", "magicDef", "buff", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1), new(24018, 1) }),
                    new(new MnemeSlot[] { new(24016, 1), new(24037, 1), new(24020, 1) }),
                }),
            new(
                actionId: 12967,
                magiaIndex: 10,
                fallbackName: "Wisdom of the Breathtaker",
                iconId: 64610,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "all" },
                tags: new[] { "poison", "movementSpeed", "mountSpeed", "eva", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24810, 1) }),
                    new(new MnemeSlot[] { new(24025, 1), new(24029, 1) }),
                    new(new MnemeSlot[] { new(24029, 3) }),
                    new(new MnemeSlot[] { new(24025, 3) }),
                }),
            new(
                actionId: 12968,
                magiaIndex: 11,
                fallbackName: "Spirit of the Remembered",
                iconId: 64611,
                kind: LogosActionKind.Ability,
                uses: 1,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "all" },
                tags: new[] { "maxHP", "acc", "raise", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24021, 1) }),
                    new(new MnemeSlot[] { new(24016, 1), new(24018, 1) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24016, 1), new(24017, 1) }),
                }),
            new(
                actionId: 12969,
                magiaIndex: 12,
                fallbackName: "Protect L",
                iconId: 64612,
                kind: LogosActionKind.Spell,
                uses: 0,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "physicalDef", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24022, 1) }),
                }),
            new(
                actionId: 12970,
                magiaIndex: 13,
                fallbackName: "Shell L",
                iconId: 64613,
                kind: LogosActionKind.Spell,
                uses: 0,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "magicDef", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24023, 1) }),
                    new(new MnemeSlot[] { new(24036, 1), new(24022, 1) }),
                }),
            new(
                actionId: 12971,
                magiaIndex: 14,
                fallbackName: "Death L",
                iconId: 64641,
                kind: LogosActionKind.Spell,
                uses: 30,
                cast: 5f,
                recast: 300f,
                jobs: new[] { "all" },
                tags: new[] { "ko" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24038, 1), new(24027, 1) }),
                    new(new MnemeSlot[] { new(24038, 1), new(24031, 2) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24024, 1), new(24038, 1) }),
                    new(new MnemeSlot[] { new(24027, 3) }),
                }),
            new(
                actionId: 12972,
                magiaIndex: 15,
                fallbackName: "Focus L",
                iconId: 64642,
                kind: LogosActionKind.Ability,
                uses: 99,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "weaponskillPotency", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1), new(24032, 1) }),
                    new(new MnemeSlot[] { new(24032, 3) }),
                }),
            new(
                actionId: 12973,
                magiaIndex: 16,
                fallbackName: "Paralyze L",
                iconId: 64614,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "paralysis", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24024, 1) }),
                }),
            new(
                actionId: 12974,
                magiaIndex: 17,
                fallbackName: "Paralyze L III",
                iconId: 64615,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "paralysis", "aoe", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24024, 1), new(24026, 1) }),
                    new(new MnemeSlot[] { new(24024, 3) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24024, 2) }),
                }),
            new(
                actionId: 12975,
                magiaIndex: 18,
                fallbackName: "Swift L",
                iconId: 64643,
                kind: LogosActionKind.Ability,
                uses: 20,
                cast: 0f,
                recast: 90f,
                jobs: new[] { "all" },
                tags: new[] { "movementSpeed", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24025, 2) }),
                    new(new MnemeSlot[] { new(24030, 2), new(24025, 1) }),
                }),
            new(
                actionId: 12976,
                magiaIndex: 19,
                fallbackName: "Featherfoot L",
                iconId: 64616,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 90f,
                jobs: new[] { "all" },
                tags: new[] { "eva", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24025, 1) }),
                    new(new MnemeSlot[] { new(24028, 2) }),
                }),
            new(
                actionId: 12977,
                magiaIndex: 20,
                fallbackName: "Spirit Dart L",
                iconId: 64617,
                kind: LogosActionKind.Weaponskill,
                uses: 50,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "mnk", "drg", "brd", "blm", "smn", "nin", "mch", "sam", "rdm", "dnc" },
                tags: new[] { "rangedDmg", "dmg", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24026, 1) }),
                    new(new MnemeSlot[] { new(24031, 1), new(24019, 1) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24024, 1), new(24031, 1) }),
                }),
            new(
                actionId: 12978,
                magiaIndex: 21,
                fallbackName: "Catastrophe L",
                iconId: 64618,
                kind: LogosActionKind.Ability,
                uses: 3,
                cast: 0f,
                recast: 300f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "nin", "mch", "drk", "sam", "gnb", "dnc" },
                tags: new[] { "dmg", "aoe" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24018, 1), new(24026, 1) }),
                    new(new MnemeSlot[] { new(24032, 2) }),
                    new(new MnemeSlot[] { new(24026, 3) }),
                }),
            new(
                actionId: 12979,
                magiaIndex: 22,
                fallbackName: "Dispel L",
                iconId: 64619,
                kind: LogosActionKind.Spell,
                uses: 0,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "mnk", "drg", "brd", "whm", "blm", "smn", "sch", "nin", "mch", "ast", "sam", "rdm" },
                tags: new[] { "dispel" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24027, 1) }),
                    new(new MnemeSlot[] { new(24036, 1), new(24019, 1) }),
                    new(new MnemeSlot[] { new(24036, 3) }),
                    new(new MnemeSlot[] { new(24031, 3) }),
                }),
            new(
                actionId: 12980,
                magiaIndex: 23,
                fallbackName: "Feint L",
                iconId: 64620,
                kind: LogosActionKind.Weaponskill,
                uses: 0,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "pld", "war", "whm", "sch", "drk", "ast", "gnb" },
                tags: new[] { "dmg", "eva", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24028, 1) }),
                }),
            new(
                actionId: 12981,
                magiaIndex: 24,
                fallbackName: "Stealth L",
                iconId: 64621,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 15f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "whm", "blm", "smn", "sch", "mch", "drk", "ast", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "buff", "debuff", "movementSpeed" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24029, 1) }),
                    new(new MnemeSlot[] { new(24019, 1), new(24023, 1) }),
                }),
            new(
                actionId: 12982,
                magiaIndex: 25,
                fallbackName: "Aetherial Manipulation L",
                iconId: 64622,
                kind: LogosActionKind.Ability,
                uses: 99,
                cast: 0f,
                recast: 5f,
                jobs: new[] { "all" },
                tags: new[] { "movementSpeed" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24030, 1), new(24029, 1) }),
                    new(new MnemeSlot[] { new(24016, 1), new(24030, 1), new(24028, 1) }),
                }),
            new(
                actionId: 12983,
                magiaIndex: 26,
                fallbackName: "Backstep L",
                iconId: 64623,
                kind: LogosActionKind.Ability,
                uses: 99,
                cast: 0f,
                recast: 5f,
                jobs: new[] { "all" },
                tags: new[] { "movementSpeed" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24030, 1) }),
                }),
            new(
                actionId: 12984,
                magiaIndex: 27,
                fallbackName: "Tranquilizer L",
                iconId: 64624,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 30f,
                jobs: new[] { "all" },
                tags: new[] { "stun", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24031, 1) }),
                }),
            new(
                actionId: 12985,
                magiaIndex: 28,
                fallbackName: "Bloodbath L",
                iconId: 64625,
                kind: LogosActionKind.Ability,
                uses: 30,
                cast: 0f,
                recast: 60f,
                jobs: new[] { "all" },
                tags: new[] { "HP" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24032, 1) }),
                    new(new MnemeSlot[] { new(24033, 1), new(24020, 1) }),
                    new(new MnemeSlot[] { new(24016, 2), new(24033, 1) }),
                }),
            new(
                actionId: 12986,
                magiaIndex: 29,
                fallbackName: "Rejuvenate L",
                iconId: 64626,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 30f,
                jobs: new[] { "all" },
                tags: new[] { "HP", "MP" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24032, 1), new(24023, 1) }),
                    new(new MnemeSlot[] { new(24021, 1), new(24026, 1) }),
                    new(new MnemeSlot[] { new(24015, 1), new(24016, 1), new(24033, 1) }),
                }),
            new(
                actionId: 12987,
                magiaIndex: 30,
                fallbackName: "Haymaker L",
                iconId: 64627,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 30f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "dmg", "slow", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1), new(24025, 1) }),
                    new(new MnemeSlot[] { new(24016, 1), new(24037, 1), new(24025, 1) }),
                }),
            new(
                actionId: 12988,
                magiaIndex: 31,
                fallbackName: "Rapid Recast L",
                iconId: 64628,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 90f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "recastSpeed", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24036, 1), new(24027, 1) }),
                    new(new MnemeSlot[] { new(24033, 1), new(24036, 1), new(24028, 1) }),
                }),
            new(
                actionId: 12989,
                magiaIndex: 32,
                fallbackName: "Cure L",
                iconId: 64629,
                kind: LogosActionKind.Spell,
                uses: 0,
                cast: 2f,
                recast: 2.5f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "HP" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24033, 1) }),
                }),
            new(
                actionId: 12990,
                magiaIndex: 33,
                fallbackName: "Cure L II",
                iconId: 64630,
                kind: LogosActionKind.Ability,
                uses: 50,
                cast: 0f,
                recast: 5f,
                jobs: new[] { "mnk", "drg", "brd", "blm", "smn", "nin", "mch", "sam", "rdm", "dnc" },
                tags: new[] { "HP" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24034, 1) }),
                    new(new MnemeSlot[] { new(24033, 1), new(24019, 1) }),
                    new(new MnemeSlot[] { new(24033, 3) }),
                    new(new MnemeSlot[] { new(24038, 3) }),
                }),
            new(
                actionId: 12991,
                magiaIndex: 34,
                fallbackName: "Stoneskin L",
                iconId: 64631,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 2f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24035, 1) }),
                    new(new MnemeSlot[] { new(24022, 1), new(24023, 1) }),
                    new(new MnemeSlot[] { new(24022, 3) }),
                    new(new MnemeSlot[] { new(24023, 3) }),
                }),
            new(
                actionId: 12992,
                magiaIndex: 35,
                fallbackName: "Cure L III",
                iconId: 64632,
                kind: LogosActionKind.Spell,
                uses: 50,
                cast: 2f,
                recast: 2.5f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "HP", "aoe" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24032, 1), new(24019, 1) }),
                    new(new MnemeSlot[] { new(24034, 2) }),
                    new(new MnemeSlot[] { new(24033, 2), new(24019, 1) }),
                }),
            new(
                actionId: 12993,
                magiaIndex: 36,
                fallbackName: "Regen L",
                iconId: 64633,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "HP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24031, 1), new(24034, 1) }),
                    new(new MnemeSlot[] { new(24028, 1), new(24034, 1) }),
                    new(new MnemeSlot[] { new(24033, 2), new(24028, 1) }),
                }),
            new(
                actionId: 12994,
                magiaIndex: 37,
                fallbackName: "Esuna L",
                iconId: 64634,
                kind: LogosActionKind.Spell,
                uses: 0,
                cast: 1f,
                recast: 2.5f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "esuna" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24036, 1) }),
                }),
            new(
                actionId: 12995,
                magiaIndex: 38,
                fallbackName: "Incense L",
                iconId: 64644,
                kind: LogosActionKind.Ability,
                uses: 0,
                cast: 0f,
                recast: 20f,
                jobs: new[] { "mnk", "drg", "brd", "whm", "blm", "smn", "sch", "nin", "mch", "ast", "sam", "rdm", "dnc" },
                tags: new[] { "enmity" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24037, 1) }),
                }),
            new(
                actionId: 12996,
                magiaIndex: 39,
                fallbackName: "Raise L",
                iconId: 64645,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 3f,
                recast: 2.5f,
                jobs: new[] { "pld", "mnk", "war", "drg", "brd", "blm", "smn", "nin", "mch", "drk", "sam", "rdm", "gnb", "dnc" },
                tags: new[] { "raise" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24038, 1) }),
                }),
            new(
                actionId: 12997,
                magiaIndex: 40,
                fallbackName: "Bravery L",
                iconId: 64635,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "whm", "blm", "smn", "sch", "ast", "rdm" },
                tags: new[] { "dmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 1), new(24018, 1), new(24019, 1) }),
                }),
            new(
                actionId: 12998,
                magiaIndex: 41,
                fallbackName: "Solid Shield L",
                iconId: 64636,
                kind: LogosActionKind.Ability,
                uses: 30,
                cast: 0f,
                recast: 300f,
                jobs: new[] { "mnk", "drg", "brd", "whm", "blm", "smn", "sch", "nin", "mch", "ast", "sam", "rdm", "dnc" },
                tags: new[] { "physicalDmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24022, 1), new(24018, 1), new(24035, 1) }),
                }),
            new(
                actionId: 12999,
                magiaIndex: 42,
                fallbackName: "Spell Shield L",
                iconId: 64637,
                kind: LogosActionKind.Ability,
                uses: 30,
                cast: 0f,
                recast: 300f,
                jobs: new[] { "mnk", "drg", "brd", "whm", "blm", "smn", "sch", "nin", "mch", "ast", "sam", "rdm", "dnc" },
                tags: new[] { "magicDmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24018, 1), new(24023, 1), new(24035, 1) }),
                }),
            new(
                actionId: 13000,
                magiaIndex: 43,
                fallbackName: "Reflect L",
                iconId: 64646,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "all" },
                tags: new[] { "magicDmg", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24022, 1), new(24019, 1), new(24023, 1) }),
                }),
            new(
                actionId: 13001,
                magiaIndex: 44,
                fallbackName: "Smite L",
                iconId: 64638,
                kind: LogosActionKind.Ability,
                uses: 30,
                cast: 0f,
                recast: 45f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "dmg", "HP" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24031, 1), new(24020, 1), new(24026, 1) }),
                }),
            new(
                actionId: 13002,
                magiaIndex: 45,
                fallbackName: "Refresh L",
                iconId: 64647,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 3f,
                recast: 2.5f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "MP", "aoe", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24015, 1), new(24019, 1), new(24034, 1) }),
                }),
            new(
                actionId: 13003,
                magiaIndex: 46,
                fallbackName: "Banish L",
                iconId: 64639,
                kind: LogosActionKind.Spell,
                uses: 99,
                cast: 2.5f,
                recast: 2.5f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "dmg", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24015, 1), new(24027, 2) }),
                }),
            new(
                actionId: 13004,
                magiaIndex: 47,
                fallbackName: "Banish L III",
                iconId: 64640,
                kind: LogosActionKind.Spell,
                uses: 50,
                cast: 3f,
                recast: 2.5f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "dmg", "aoe", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24019, 1), new(24027, 2) }),
                }),
            new(
                actionId: 13005,
                magiaIndex: 48,
                fallbackName: "Magic Burst L",
                iconId: 64648,
                kind: LogosActionKind.Ability,
                uses: 10,
                cast: 0f,
                recast: 90f,
                jobs: new[] { "whm", "blm", "smn", "sch", "ast", "rdm" },
                tags: new[] { "magicDmg", "MP", "buff", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24813, 1) }),
                    new(new MnemeSlot[] { new(24021, 1), new(24019, 1), new(24035, 1) }),
                }),
            new(
                actionId: 13006,
                magiaIndex: 49,
                fallbackName: "Double Edge L",
                iconId: 64649,
                kind: LogosActionKind.Ability,
                uses: 10,
                cast: 0f,
                recast: 90f,
                jobs: new[] { "pld", "mnk", "war", "drg", "nin", "drk", "sam", "gnb" },
                tags: new[] { "physicalDmg", "dmg", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24812, 1) }),
                    new(new MnemeSlot[] { new(24020, 1), new(24032, 1), new(24018, 1) }),
                }),
            new(
                actionId: 13007,
                magiaIndex: 50,
                fallbackName: "Eagle Eye Shot L",
                iconId: 64650,
                kind: LogosActionKind.Weaponskill,
                uses: 30,
                cast: 0f,
                recast: 2.5f,
                jobs: new[] { "brd", "mch", "dnc" },
                tags: new[] { "rangedDmg", "enmity" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24811, 1) }),
                    new(new MnemeSlot[] { new(24020, 1), new(24021, 1), new(24026, 1) }),
                }),
            new(
                actionId: 14476,
                magiaIndex: 51,
                fallbackName: "Perception L",
                iconId: 64651,
                kind: LogosActionKind.Ability,
                uses: 99,
                cast: 0f,
                recast: 3.5f,
                jobs: new[] { "mnk", "drg", "brd", "blm", "smn", "nin", "mch", "sam", "rdm", "dnc" },
                tags: new[] { "dungeon" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24810, 2) }),
                    new(new MnemeSlot[] { new(24029, 1), new(24027, 1), new(24810, 1) }),
                }),
            new(
                actionId: 14477,
                magiaIndex: 52,
                fallbackName: "Wisdom of the Elder",
                iconId: 64652,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "blm", "smn", "rdm" },
                tags: new[] { "magicDmg", "magicDef", "MP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24015, 1), new(24019, 1), new(24813, 1) }),
                    new(new MnemeSlot[] { new(24018, 1), new(24035, 1), new(24813, 1) }),
                }),
            new(
                actionId: 14478,
                magiaIndex: 53,
                fallbackName: "Wisdom of the Duelist",
                iconId: 64653,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "mnk", "drg", "nin", "sam" },
                tags: new[] { "dmg", "physicalDmg", "maxHP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24020, 2), new(24812, 1) }),
                    new(new MnemeSlot[] { new(24030, 1), new(24032, 1), new(24812, 1) }),
                }),
            new(
                actionId: 14479,
                magiaIndex: 54,
                fallbackName: "Wisdom of the Fiendhunter",
                iconId: 64654,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "brd", "mch", "dnc" },
                tags: new[] { "physicalDmg", "eva", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24025, 1), new(24026, 1), new(24811, 1) }),
                    new(new MnemeSlot[] { new(24028, 1), new(24031, 1), new(24811, 1) }),
                }),
            new(
                actionId: 14480,
                magiaIndex: 55,
                fallbackName: "Wisdom of the Indomitable",
                iconId: 64655,
                kind: LogosActionKind.Spell,
                uses: 3,
                cast: 0f,
                recast: 10f,
                jobs: new[] { "pld", "war", "drk", "gnb" },
                tags: new[] { "def", "maxHP", "buff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24017, 1), new(24037, 1), new(24812, 1) }),
                    new(new MnemeSlot[] { new(24022, 1), new(24021, 1), new(24812, 1) }),
                }),
            new(
                actionId: 14481,
                magiaIndex: 56,
                fallbackName: "Sacrifice L",
                iconId: 64656,
                kind: LogosActionKind.Spell,
                uses: 10,
                cast: 3f,
                recast: 2.5f,
                jobs: new[] { "whm", "sch", "ast" },
                tags: new[] { "raise", "debuff" },
                recipes: new LogosRecipe[]
                {
                    new(new MnemeSlot[] { new(24036, 1), new(24038, 1), new(24813, 1) }),
                }),
        };

        public static readonly int Total = Actions.Count;

        private static readonly Dictionary<uint, LogosAction> byId = BuildIndex();

        private static Dictionary<uint, LogosAction> BuildIndex()
        {
            var map = new Dictionary<uint, LogosAction>(Actions.Count);
            foreach (var a in Actions) map[a.ActionId] = a;
            return map;
        }

        public static bool TryGet(uint actionId, out LogosAction action) =>
            byId.TryGetValue(actionId, out action!);

        private static readonly Dictionary<uint, LogosAction> byMagiaIndex = BuildMagiaIndex();

        private static Dictionary<uint, LogosAction> BuildMagiaIndex()
        {
            var map = new Dictionary<uint, LogosAction>(Actions.Count);
            foreach (var a in Actions) if (a.MagiaIndex != 0) map[a.MagiaIndex] = a;
            return map;
        }

        /// <summary>Looks up by the Logos Action Log's own 1-56 index.</summary>
        public static LogosAction? ByMagiaIndex(uint magiaIndex) =>
            byMagiaIndex.TryGetValue(magiaIndex, out var a) ? a : null;

        public static LogosAction? ById(uint actionId) =>
            byId.TryGetValue(actionId, out var a) ? a : null;

        /// <summary>Every mneme item id referenced by any recipe.</summary>
        public static IEnumerable<uint> AllMnemeItemIds()
        {
            var seen = new HashSet<uint>();
            foreach (var action in Actions)
                foreach (var recipe in action.Recipes)
                    foreach (var slot in recipe.Slots)
                        if (seen.Add(slot.ItemId)) yield return slot.ItemId;
        }
    }
}
