// <auto-generated>
//   Generated from live FFXIV game data (Action / Item / EurekaMagiciteItem sheets)
//   cross-referenced with the public recipe tables at https://ffxiv-eureka.com/logograms.
//   Do not edit by hand. Regenerate with the tooling described in Data/README.md.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace Logoria.Data
{
    /// <summary>
    /// A mneme's category, straight from the game's EurekaMagiciteItemType sheet.
    /// Note this is NOT the same as which logogram yields it: the Conceptual,
    /// Fundamental and Obscure logograms each contain a mix of categories.
    /// </summary>
    public enum MnemeCategory
    {
        Curative,
        Inimical,
        Mitigative,
        Offensive,
        Protective,
        Tactical,
    }

    /// <summary>An unidentified logogram, which appraises into one of several mnemes.</summary>
    /// <param name="AcquiredBy">Source tags, e.g. "coffer-gold", "NM-protective".</param>
    public sealed record Logogram(
        int Index,
        uint ItemId,
        string FallbackName,
        ushort IconId,
        IReadOnlyList<string> AcquiredBy);

    /// <summary>A deciphered mneme: the actual crafting input for a Logos Action.</summary>
    /// <param name="ItemId">Real game Item row id.</param>
    /// <param name="LogogramIndex">Which logogram yields this mneme.</param>
    public sealed record Mneme(
        uint ItemId,
        string FallbackName,
        ushort IconId,
        MnemeCategory Category,
        int LogogramIndex);

    public static class MnemeDatabase
    {
        public static readonly IReadOnlyList<Mneme> All = new Mneme[]
        {
            new(24015, "Wisdom of the Aetherweaver", 27952, MnemeCategory.Offensive, 1),
            new(24016, "Wisdom of the Martialist", 27952, MnemeCategory.Offensive, 1),
            new(24017, "Wisdom of the Platebearer", 27951, MnemeCategory.Protective, 1),
            new(24018, "Wisdom of the Guardian", 27951, MnemeCategory.Protective, 4),
            new(24019, "Wisdom of the Ordained", 27953, MnemeCategory.Curative, 5),
            new(24020, "Wisdom of the Skirmisher", 27952, MnemeCategory.Offensive, 3),
            new(24021, "Spirit of the Remembered", 27951, MnemeCategory.Protective, 4),
            new(24022, "Protect L", 27956, MnemeCategory.Mitigative, 2),
            new(24023, "Shell L", 27956, MnemeCategory.Mitigative, 8),
            new(24024, "Paralyze L", 27955, MnemeCategory.Inimical, 1),
            new(24025, "Featherfoot L", 27954, MnemeCategory.Tactical, 6),
            new(24026, "Spirit Dart L", 27955, MnemeCategory.Inimical, 7),
            new(24027, "Dispel L", 27955, MnemeCategory.Inimical, 7),
            new(24028, "Feint L", 27954, MnemeCategory.Tactical, 2),
            new(24029, "Stealth L", 27954, MnemeCategory.Tactical, 6),
            new(24030, "Backstep L", 27954, MnemeCategory.Tactical, 1),
            new(24031, "Tranquilizer L", 27955, MnemeCategory.Inimical, 2),
            new(24032, "Bloodbath L", 27952, MnemeCategory.Offensive, 3),
            new(24033, "Cure L", 27953, MnemeCategory.Curative, 1),
            new(24034, "Cure L II", 27953, MnemeCategory.Curative, 5),
            new(24035, "Stoneskin L", 27956, MnemeCategory.Mitigative, 8),
            new(24036, "Esuna L", 27953, MnemeCategory.Curative, 2),
            new(24037, "Incense L", 27951, MnemeCategory.Protective, 1),
            new(24038, "Raise L", 27953, MnemeCategory.Curative, 2),
            new(24810, "Wisdom of the Breathtaker", 27954, MnemeCategory.Tactical, 9),
            new(24811, "Eagle Eye Shot L", 27952, MnemeCategory.Offensive, 9),
            new(24812, "Double Edge L", 27952, MnemeCategory.Offensive, 9),
            new(24813, "Magic Burst L", 27952, MnemeCategory.Offensive, 9),
        };

        public static readonly IReadOnlyList<Logogram> Logograms = new Logogram[]
        {
            new(1, 24007, "Conceptual Logogram", 20034, new[] { "sprite-conceptual", "coffer-bronze" }),
            new(2, 24008, "Fundamental Logogram", 20035, new[] { "sprite-fundamental", "coffer-bronze", "chain-30" }),
            new(3, 24010, "Offensive Logogram", 20036, new[] { "coffer-gold" }),
            new(4, 24011, "Protective Logogram", 20036, new[] { "coffer-gold", "NM-protective" }),
            new(5, 24009, "Curative Logogram", 20036, new[] { "coffer-silver", "NM-curative" }),
            new(6, 24012, "Tactical Logogram", 20036, new[] { "heatbox" }),
            new(7, 24014, "Inimical Logogram", 20036, new[] { "sprite-adaptation-inimical", "NM-inimical" }),
            new(8, 24013, "Mitigative Logogram", 20036, new[] { "sprite-mitigative", "sprite-adaptation-mitigative", "undead-adaptation" }),
            new(9, 24809, "Obscure Logogram", 20036, new[] { "NM-obscure", "chain-30" }),
        };

        private static readonly Dictionary<uint, Mneme> byId = BuildIndex();

        private static Dictionary<uint, Mneme> BuildIndex()
        {
            var map = new Dictionary<uint, Mneme>(All.Count);
            foreach (var m in All) map[m.ItemId] = m;
            return map;
        }

        public static Mneme? ById(uint itemId) => byId.TryGetValue(itemId, out var m) ? m : null;

        public static Logogram? LogogramAt(int index)
        {
            foreach (var l in Logograms) if (l.Index == index) return l;
            return null;
        }

        /// <summary>The logogram that yields this mneme, if known.</summary>
        public static Logogram? SourceOf(uint mnemeItemId)
        {
            var mneme = ById(mnemeItemId);
            return mneme == null ? null : LogogramAt(mneme.LogogramIndex);
        }
    }
}
