// Generates Logoria's Data/*.g.cs from the validated logoria_db.json.
const fs = require('fs');
const path = require('path');

const scratch = __dirname;                              // Tools\
const outDir = path.resolve(__dirname, '..', 'Data');   // Logoria\Data
const db = JSON.parse(fs.readFileSync(path.join(scratch, 'logoria_db.json'), 'utf8'));

const banner = `// <auto-generated>
//   Generated from live FFXIV game data (Action / Item / EurekaMagiciteItem sheets)
//   cross-referenced with the public recipe tables at https://ffxiv-eureka.com/logograms.
//   Do not edit by hand. Regenerate with the tooling described in Data/README.md.
// </auto-generated>

#nullable enable
`;

// ---------- Mnemes and logograms ----------
const mnemeLines = db.mnemes
  .sort((a, b) => a.itemId - b.itemId)
  .map(m => `            new(${m.itemId}, "${m.name}", ${m.icon}, MnemeCategory.${cap(m.category)}, ${m.logogramIdx}),`);

const categories = [...new Set(db.mnemes.map(m => m.category))].sort();

const logogramLines = db.logograms
  .sort((a, b) => a.idx - b.idx)
  .map(l => {
    const by = l.acquiredBy.map(s => `"${s}"`).join(', ');
    return `            new(${l.idx}, ${l.itemId}, "${l.name}", ${l.icon}, new[] { ${by} }),`;
  });

const mnemeFile = `${banner}
using System.Collections.Generic;

namespace Logoria.Data
{
    /// <summary>
    /// A mneme's category, straight from the game's EurekaMagiciteItemType sheet.
    /// Note this is NOT the same as which logogram yields it: the Conceptual,
    /// Fundamental and Obscure logograms each contain a mix of categories.
    /// </summary>
    public enum MnemeCategory
    {
${categories.map(k => `        ${cap(k)},`).join('\n')}
    }

    /// <summary>An unidentified logogram, which appraises into one of several mnemes.</summary>
    /// <param name="AcquiredBy">Source tags, e.g. "coffer-gold", "NM-protective".</param>
    public sealed record Logogram(
        int Index,
        uint ItemId,
        string FallbackName,
        ushort IconId,
        IReadOnlyList<string> AcquiredBy);

    /// <summary>A deciphered mneme: the actual crafting input for a Logos Action.</summary>
    /// <param name="ItemId">Real game Item row id.</param>
    /// <param name="LogogramIndex">Which logogram yields this mneme.</param>
    public sealed record Mneme(
        uint ItemId,
        string FallbackName,
        ushort IconId,
        MnemeCategory Category,
        int LogogramIndex);

    public static class MnemeDatabase
    {
        public static readonly IReadOnlyList<Mneme> All = new Mneme[]
        {
${mnemeLines.join('\n')}
        };

        public static readonly IReadOnlyList<Logogram> Logograms = new Logogram[]
        {
${logogramLines.join('\n')}
        };

        private static readonly Dictionary<uint, Mneme> byId = BuildIndex();

        private static Dictionary<uint, Mneme> BuildIndex()
        {
            var map = new Dictionary<uint, Mneme>(All.Count);
            foreach (var m in All) map[m.ItemId] = m;
            return map;
        }

        public static Mneme? ById(uint itemId) => byId.TryGetValue(itemId, out var m) ? m : null;

        public static Logogram? LogogramAt(int index)
        {
            foreach (var l in Logograms) if (l.Index == index) return l;
            return null;
        }

        /// <summary>The logogram that yields this mneme, if known.</summary>
        public static Logogram? SourceOf(uint mnemeItemId)
        {
            var mneme = ById(mnemeItemId);
            return mneme == null ? null : LogogramAt(mneme.LogogramIndex);
        }
    }
}
`;

// ---------- Actions ----------
function recipeLiteral(r) {
  const slots = r.map(s => `new(${s.itemId}, ${s.count})`).join(', ');
  return `new(new MnemeSlot[] { ${slots} })`;
}

const actionLines = db.actions.map(a => {
  const jobs = a.jobs.map(j => `"${j}"`).join(', ');
  const tags = a.tags.map(t => `"${t}"`).join(', ');
  const recipes = a.recipes.map(recipeLiteral).join(',\n                    ');
  return `            new(
                actionId: ${a.actionId},
                magiaIndex: ${a.magiaIndex},
                fallbackName: "${a.name}",
                iconId: ${a.icon},
                kind: LogosActionKind.${cap(a.type)},
                uses: ${a.uses},
                cast: ${fl(a.cast)},
                recast: ${fl(a.recast)},
                jobs: new[] { ${jobs} },
                tags: new[] { ${tags} },
                recipes: new LogosRecipe[]
                {
                    ${recipes},
                }),`;
});

const actionKinds = [...new Set(db.actions.map(a => a.type))].sort();

const actionFile = `${banner}
using System.Collections.Generic;

namespace Logoria.Data
{
    public enum LogosActionKind
    {
${actionKinds.map(k => `        ${cap(k)},`).join('\n')}
    }

    /// <summary>One mneme requirement within a recipe.</summary>
    public sealed record MnemeSlot(uint ItemId, int Count);

    /// <summary>One way to synthesise an action. Fewer slots means a higher success rate.</summary>
    public sealed record LogosRecipe(IReadOnlyList<MnemeSlot> Slots)
    {
        public int TotalMnemes
        {
            get
            {
                var n = 0;
                foreach (var s in Slots) n += s.Count;
                return n;
            }
        }
    }

    public static class LogosDatabase
    {
        public static readonly IReadOnlyList<LogosAction> Actions = new LogosAction[]
        {
${actionLines.join('\n')}
        };

        public static readonly int Total = Actions.Count;

        private static readonly Dictionary<uint, LogosAction> byId = BuildIndex();

        private static Dictionary<uint, LogosAction> BuildIndex()
        {
            var map = new Dictionary<uint, LogosAction>(Actions.Count);
            foreach (var a in Actions) map[a.ActionId] = a;
            return map;
        }

        public static bool TryGet(uint actionId, out LogosAction action) =>
            byId.TryGetValue(actionId, out action!);

        private static readonly Dictionary<uint, LogosAction> byMagiaIndex = BuildMagiaIndex();

        private static Dictionary<uint, LogosAction> BuildMagiaIndex()
        {
            var map = new Dictionary<uint, LogosAction>(Actions.Count);
            foreach (var a in Actions) if (a.MagiaIndex != 0) map[a.MagiaIndex] = a;
            return map;
        }

        /// <summary>Looks up by the Logos Action Log's own 1-56 index.</summary>
        public static LogosAction? ByMagiaIndex(uint magiaIndex) =>
            byMagiaIndex.TryGetValue(magiaIndex, out var a) ? a : null;

        public static LogosAction? ById(uint actionId) =>
            byId.TryGetValue(actionId, out var a) ? a : null;

        /// <summary>Every mneme item id referenced by any recipe.</summary>
        public static IEnumerable<uint> AllMnemeItemIds()
        {
            var seen = new HashSet<uint>();
            foreach (var action in Actions)
                foreach (var recipe in action.Recipes)
                    foreach (var slot in recipe.Slots)
                        if (seen.Add(slot.ItemId)) yield return slot.ItemId;
        }
    }
}
`;

fs.writeFileSync(path.join(outDir, 'MnemeDatabase.g.cs'), mnemeFile);
fs.writeFileSync(path.join(outDir, 'LogosDatabase.g.cs'), actionFile);

console.log('MnemeDatabase.g.cs :', mnemeFile.split('\n').length, 'lines,', db.mnemes.length, 'mnemes');
console.log('LogosDatabase.g.cs :', actionFile.split('\n').length, 'lines,', db.actions.length, 'actions');
console.log('mneme categories   :', categories.join(', '));
console.log('logograms          :', db.logograms.length);
console.log('action kinds       :', actionKinds.join(', '));

function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
function fl(n) { return Number.isInteger(n) ? `${n}f` : `${n}f`; }
